---
{{- if .Values.ingress.enabled -}}
{{- if .Values.service.processors.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apache-nifi.fullname" $ }}-api-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.service.processors.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.service.processors.host | quote }}
      http:
        paths:
        {{- range .Values.service.processors.ports  }}
          - path: /{{ .name }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "apache-nifi.fullname" $ }}
                port: 
                  number: {{ .port }}
         {{- end }}
{{- end }}
{{- end }}
